[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crypto_bet_escrow = "Da9ntLekG2xkGhZPxSZwxnwZqh43q8KZCaHHbutq9BMM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/xatxay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
